### ISSUE TITLE
Change nav styles

### ISSUE THREAD

**Issue by troyvassalotti** [troyvassalotti/troyv.dev#204]
```css
ul {
  display: flex;
}

li:first-of-type {
  inline-size: 100%;
}

li {
  display: inline-block
}
```

Something like that to prevent white-space from interfering with the spacing in the list items as it does on the music's listening habits page.
